# Pre-commit hooks configuration
# Install: pre-commit install
# Run: pre-commit run --all-files
# Run before push: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8  # Match Makefile and CI
    hooks:
      # Format code (Black-compatible)
      - id: ruff-format
        name: Format code with Ruff
      # Lint code (flake8 + isort + more)
      - id: ruff
        name: Lint code with Ruff
        args: [--fix, --unsafe-fixes]

  # Mypy - Static type checker (run in CI instead for reliability)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.17.1  # Match pyproject.toml strict settings
  #   hooks:
  #     - id: mypy
  #       name: Type check with Mypy
  #       # Match Makefile: check src and tests in strict mode
  #       args: [--strict, src, tests]
  #       exclude: ^(src/domain/protocols\.py|tests/conftest\.py)$
  #       additional_dependencies:
  #         - pydantic>=2.6.0
  #         - httpx>=0.27.0
  #         - slack-sdk>=3.27.0

  # Tests are run in CI/CD via GitHub Actions, not pre-commit

  # Security - Check for secrets and vulnerabilities
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.5.0
  #   hooks:
  #     - id: detect-secrets
  #       name: Detect secrets
  #       args: [--baseline, .secrets.baseline]
  #       exclude: ^(tests/|docs/|\.env\.example)

  # Trailing whitespace and end-of-file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Add missing end-of-file
        exclude: ^(alembic/versions/.*\.py)$
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-added-large-files
        name: Check for large files
        args: [--maxkb=500]
