# Slack Event Manager Configuration
# This file contains non-sensitive application settings
# Secrets (tokens, API keys) are stored in .env file

# LLM Configuration
llm:
  model: gpt-5-nano
  temperature: 1.0  # gpt-5-nano only supports 1.0
  timeout_seconds: 120
  daily_budget_usd: 10.0
  max_events_per_msg: 5

# Database Configuration
database:
  path: data/slack_events.db

# Slack Configuration
slack:
  digest_channel_id: C06B5NJLY4B  # Channel for publishing digests
  lookback_hours_default: 24  # Default lookback for message ingestion

# Processing Configuration
processing:
  tz_default: Europe/Amsterdam
  threshold_score_default: 0.0  # 0.0 = process all messages

# Deduplication Configuration
deduplication:
  date_window_hours: 48
  title_similarity: 0.8
  message_lookback_days: 30

# Digest Configuration
digest:
  max_events: 10  # Default maximum events per digest (null = unlimited)
  min_confidence: 0.7  # Minimum confidence score to include (0.0-1.0)
  lookback_hours: 48  # Default lookback window for events
  category_priorities:
    product: 1
    risk: 2
    process: 3
    marketing: 4
    org: 5
    unknown: 6

# Importance Scoring Configuration
importance:
  min_publish_threshold: 60  # Minimum importance to publish (0-100)
  high_priority_threshold: 80  # Threshold for high-priority events
  category_base_scores:
    product: 30
    risk: 35
    process: 20
    marketing: 15
    org: 25
    unknown: 10
  critical_subsystems:
    - authentication
    - payment
    - trading
    - wallet
    - database
    - api-gateway

# Validation Configuration
validation:
  min_confidence: 0.6  # Minimum confidence for quality filter
  max_title_length: 140
  max_qualifiers: 2
  max_links: 3
  max_impact_area: 3

# Monitored Slack Channels
channels:
  # - channel_id: C06B5NJLY4B
  #   channel_name: product-alerts-test
  #   threshold_score: 0.0
  #   keyword_weight: 0.0
  #   whitelist_keywords:
  #     - release
  #     - deploy
  #     - launch
  #     - update
  #     - new
  #     - announcement
  #     - scheduled
  #     - security
  #     - metrics
  #     - maintenance
  #     - incident
  #     - daily
  #     - weekly
  #     - monthly
  #     - report
  #     - summary
  #     - alert

  - channel_id: C04V0TK7UG6
    channel_name: releases
    threshold_score: 0.0
    keyword_weight: 0.0
    whitelist_keywords:
      - release
      - deploy
      - launch
      - update
      - new
      - announcement
      - scheduled
      - security
      - metrics
      - maintenance
      - incident
      - daily
      - weekly
      - monthly
      - report
      - summary
      - alert

  - channel_id: C0770K7FV43
    channel_name: t-onboarding-activation
    threshold_score: 0.0
    keyword_weight: 0.0
    whitelist_keywords:
      - release
      - deploy
      - launch
      - update
      - new
      - announcement
      - scheduled
      - security
      - metrics
      - maintenance
      - incident
      - daily
      - weekly
      - monthly
      - report
      - summary
      - alert

  - channel_id: C04UCRJ7UTF
    channel_name: t-product
    threshold_score: 0.0
    keyword_weight: 0.0

  - channel_id: C06A6CTK118
    channel_name: t-analytics-and-research
    threshold_score: 0.0
    keyword_weight: 0.0

# Observability
logging:
  level: INFO
