# Slack Channels Configuration Example
#
# List of Slack channels to monitor for events
# Replace with your actual channel IDs and names

channels:
  # Example: Product releases channel
  - channel_id: C1234567890
    channel_name: releases
    threshold_score: 0.0
    keyword_weight: 0.0
    whitelist_keywords:
      - release
      - deploy
      - launch
      - update
      - new
      - announcement
      - scheduled
      - security
      - metrics
      - maintenance
      - incident
      - daily
      - weekly
      - monthly
      - report
      - summary
      - alert

  # Example: Product updates channel
  - channel_id: C0987654321
    channel_name: product-updates
    threshold_score: 0.0
    keyword_weight: 0.0
    whitelist_keywords:
      - release
      - deploy
      - launch
      - update
      - new
      - announcement

  # Example: Engineering team channel
  - channel_id: C1111111111
    channel_name: team-engineering
    threshold_score: 0.0
    keyword_weight: 0.0
