# Slack Event Manager - Main Configuration Example
# Copy this to config/main.yaml and customize with your settings
#
# IMPORTANT: This file contains ONLY main settings (llm, database, processing, etc.)
# Channels configuration is in config/defaults/channels.example.yaml
# Object registry is in config/defaults/object_registry.example.yaml

# LLM Configuration
llm:
  model: gpt-5-nano
  temperature: 1.0  # gpt-5-nano only supports 1.0
  timeout_seconds: 120
  daily_budget_usd: 10.0
  max_events_per_msg: 5
  cache_ttl_days: 21  # Purge cached LLM responses after 21 days

# Database Configuration
database:
  path: data/slack_events.db

# Slack Configuration
slack:
  digest_channel_id: C1234567890  # Channel for publishing digests
  lookback_hours_default: 24  # Default lookback for message ingestion

# Processing Configuration
processing:
  tz_default: Europe/Amsterdam
  threshold_score_default: 0.0  # 0.0 = process all messages

# Deduplication Configuration
deduplication:
  date_window_hours: 48
  title_similarity: 0.8
  message_lookback_days: 30

# Digest Configuration
digest:
  max_events: 10  # Default maximum events per digest (null = unlimited)
  min_confidence: 0.7  # Minimum confidence score to include (0.0-1.0)
  lookback_hours: 48  # Default lookback window for events
  category_priorities:
    product: 1
    risk: 2
    process: 3
    marketing: 4
    org: 5
    unknown: 6

# Importance Scoring Configuration
importance:
  min_publish_threshold: 60  # Minimum importance to publish (0-100)
  high_priority_threshold: 80  # Threshold for high-priority events
  category_base_scores:
    product: 30
    risk: 35
    process: 20
    marketing: 15
    org: 25
    unknown: 10
  critical_subsystems:
    - authentication
    - payment
    - trading
    - wallet
    - database
    - api-gateway

# Validation Configuration
validation:
  min_confidence: 0.6  # Minimum confidence for quality filter
  max_title_length: 140
  max_qualifiers: 2
  max_links: 3
  max_impact_area: 3

# Observability
logging:
  level: INFO

# Telegram Configuration (optional)
# Uncomment and configure if using Telegram integration
# telegram:
#   session_path: data/telegram_session  # Path to session file (without .session extension)
#   channels:  # Configure in config/telegram_channels.yaml instead
