name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff (format check)
        run: |
          python -m ruff format --check .

      - name: Ruff (lint)
        run: |
          python -m ruff check .

      - name: Mypy (strict)
        run: |
          python -m mypy --strict src tests

      - name: Run tests with coverage
        env:
          SLACK_BOT_TOKEN: dummy-token
          OPENAI_API_KEY: dummy-key
        run: |
          python -m pytest

      - name: Upload coverage HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
