name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: Install linting tools only
        run: |
          uv pip install --system ruff==0.12.8

      - name: Ruff (format check)
        run: |
          python -m ruff format --check .

      - name: Ruff (lint)
        run: |
          python -m ruff check .

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt

      - name: Mypy (strict)
        run: |
          python -m mypy src --config-file pyproject.toml

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt

      - name: Run tests with coverage
        env:
          SLACK_BOT_TOKEN: dummy-token
          OPENAI_API_KEY: dummy-key
        run: |
          python -m pytest

      - name: Upload coverage HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
