name: Pre-commit Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: false

      - name: Install pre-commit and dependencies
        run: |
          uv pip install --python $(which python) pre-commit
          uv pip install --python $(which python) -r requirements.txt

      - name: Run pre-commit hooks (fastest feedback)
        run: |
          pre-commit run --all-files --show-diff-on-failure
